In [4]:
import pandas as pd

In [5]:
#Load Cleaned Data
df=pd.read_excel('data/Cleaned_Afficionado_Coffee_Data.xlsx')

Revenue Computation

In [6]:
#Aggregate Revenue by Product
product_revenue = (
    df.groupby('product_detail')['revenue']
      .sum()
      .reset_index()
      .sort_values(by='revenue', ascending=False)
)

print(product_revenue.head())

                  product_detail   revenue
75  Sustainably Grown Organic Lg  21151.75
20             Dark chocolate Lg  21006.00
48                      Latte Rg  19112.25
6                  Cappuccino Lg  17641.75
53       Morning Sunrise Chai Lg  17384.00

In [7]:
#Aggregate Revenue by Product Type
product_type_revenue = (
    df.groupby('product_type')['revenue']
      .sum()
      .reset_index()
      .sort_values(by='revenue', ascending=False)
)

print(product_type_revenue)

             product_type   revenue
0        Barista Espresso  91406.20
4         Brewed Chai tea  77081.95
17          Hot chocolate  72416.00
13  Gourmet brewed coffee  70034.60
3        Brewed Black tea  47932.00
6       Brewed herbal tea  47539.50
25  Premium brewed coffee  38781.15
22  Organic brewed coffee  37746.50
27                  Scone  36866.12
10            Drip coffee  31984.00
23                 Pastry  25655.99
5        Brewed Green tea  23852.50
1                Biscotti  19793.53
24          Premium Beans  14583.50
20          Organic Beans   8509.50
19             Housewares   7444.00
12          Gourmet Beans   6798.00
8                Clothing   6163.00
26          Regular syrup   6084.80
11         Espresso Beans   5560.25
7                Chai tea   4301.25
18      House blend Beans   3294.00
16             Herbal tea   2729.75
9      Drinking Chocolate   2728.04
2               Black tea   2711.85
28       Sugar free syrup   2324.00
21      Organic Chocolate   1679.60
15              Green tea   1470.75
14            Green beans   1340.00

In [8]:
#Aggregate Revenue by Product Category
category_revenue = (
    df.groupby('product_category')['revenue']
      .sum()
      .reset_index()
      .sort_values(by='revenue', ascending=False)
)

print(category_revenue)

     product_category    revenue
2              Coffee  269952.45
8                 Tea  196405.95
0              Bakery   82315.64
4  Drinking Chocolate   72416.00
3        Coffee beans   40085.25
1             Branded   13607.00
6           Loose Tea   11213.60
5            Flavours    8408.80
7  Packaged Chocolate    4407.64

In [9]:
with pd.ExcelWriter("Revenue_Analysis.xlsx") as writer:
    product_revenue.to_excel(
        writer,
        sheet_name="Product Revenue",
        index=False
    )

    product_type_revenue.to_excel(
        writer,
        sheet_name="Product Type Revenue",
        index=False
    )

    category_revenue.to_excel(
        writer,
        sheet_name="Category Revenue",
        index=False
    )

In [10]:
#Show Revenue_Analysis Sheets
excel_file = pd.ExcelFile("Revenue_Analysis.xlsx")

print(excel_file.sheet_names)

['Product Revenue', 'Product Type Revenue', 'Category Revenue']

In [11]:
#Product Revenue
print(product_revenue.head(80))

                  product_detail   revenue
75  Sustainably Grown Organic Lg  21151.75
20             Dark chocolate Lg  21006.00
48                      Latte Rg  19112.25
6                  Cappuccino Lg  17641.75
53       Morning Sunrise Chai Lg  17384.00
..                           ...       ...
49                   Lemon Grass   1360.40
36  Guatemalan Sustainably Grown   1340.00
70         Spicy Eye Opener Chai   1335.90
22                     Earl Grey   1270.90
19                Dark chocolate    755.20

[80 rows x 2 columns]

In [12]:
#product type revenue
print(product_type_revenue.head(18))

             product_type   revenue
0        Barista Espresso  91406.20
4         Brewed Chai tea  77081.95
17          Hot chocolate  72416.00
13  Gourmet brewed coffee  70034.60
3        Brewed Black tea  47932.00
6       Brewed herbal tea  47539.50
25  Premium brewed coffee  38781.15
22  Organic brewed coffee  37746.50
27                  Scone  36866.12
10            Drip coffee  31984.00
23                 Pastry  25655.99
5        Brewed Green tea  23852.50
1                Biscotti  19793.53
24          Premium Beans  14583.50
20          Organic Beans   8509.50
19             Housewares   7444.00
12          Gourmet Beans   6798.00
8                Clothing   6163.00

In [13]:
#Category revenue
print(category_revenue.head(9))

     product_category    revenue
2              Coffee  269952.45
8                 Tea  196405.95
0              Bakery   82315.64
4  Drinking Chocolate   72416.00
3        Coffee beans   40085.25
1             Branded   13607.00
6           Loose Tea   11213.60
5            Flavours    8408.80
7  Packaged Chocolate    4407.64

Product Popularity Analysis

In [14]:
#Total Units Sold per Product
product_sales = (
    df.groupby('product_detail')['transaction_qty']
      .sum()
      .reset_index()
      .sort_values(by='transaction_qty', ascending=False)
)

product_sales.head(80)

                  product_detail  transaction_qty
24                  Earl Grey Rg             4708
20             Dark chocolate Lg             4668
54       Morning Sunrise Chai Rg             4643
47                         Latte             4602
64                 Peppermint Rg             4564
..                           ...              ...
42         Jamacian Coffee River              146
22                     Earl Grey              142
36  Guatemalan Sustainably Grown              134
70         Spicy Eye Opener Chai              122
19                Dark chocolate              118

[80 rows x 2 columns]

In [15]:
#Ranking Products by Sales Volume
product_sales['rank'] = (
    product_sales['transaction_qty']
    .rank(method='dense', ascending=False)
    .astype(int)
)

product_sales.head(80)

                  product_detail  transaction_qty  rank
24                  Earl Grey Rg             4708     1
20             Dark chocolate Lg             4668     2
54       Morning Sunrise Chai Rg             4643     3
47                         Latte             4602     4
64                 Peppermint Rg             4564     5
..                           ...              ...   ...
42         Jamacian Coffee River              146    71
22                     Earl Grey              142    72
36  Guatemalan Sustainably Grown              134    73
70         Spicy Eye Opener Chai              122    74
19                Dark chocolate              118    75

[80 rows x 3 columns]

In [16]:
#Identify Top Performers
top_10_products = product_sales.head(10)

print(top_10_products)

                 product_detail  transaction_qty  rank
24                 Earl Grey Rg             4708     1
20            Dark chocolate Lg             4668     2
54      Morning Sunrise Chai Rg             4643     3
47                        Latte             4602     4
64                Peppermint Rg             4564     5
15    Columbian Medium Roast Rg             4547     6
79    Traditional Blend Chai Rg             4512     7
48                     Latte Rg             4497     8
60  Our Old Time Diner Blend Sm             4484     9
69        Serenity Green Tea Rg             4477    10

In [17]:
#Identify Bottom Performers
bottom_10_products = product_sales.tail(10)

print(bottom_10_products)

                  product_detail  transaction_qty  rank
77        Traditional Blend Chai              153    67
49                   Lemon Grass              152    68
65          Primo Espresso Roast              150    69
8                    Chili Mayan              148    70
13        Columbian Medium Roast              148    70
42         Jamacian Coffee River              146    71
22                     Earl Grey              142    72
36  Guatemalan Sustainably Grown              134    73
70         Spicy Eye Opener Chai              122    74
19                Dark chocolate              118    75

In [18]:
#Save The Result To Excel
with pd.ExcelWriter(
    "Revenue_Analysis.xlsx",
    engine="openpyxl",
    mode="a",
    if_sheet_exists="replace"
) as writer:

    product_sales.to_excel(
        writer,
        sheet_name="Product Popularity",
        index=False
    )

In [19]:
file = pd.ExcelFile("Revenue_Analysis.xlsx")

print(file.sheet_names)

['Product Revenue', 'Product Type Revenue', 'Category Revenue', 'Product Popularity']

Revenue Contribution Analysis

In [20]:
#Total Revenue per Product
product_revenue = (
    df.groupby('product_detail')['revenue']
      .sum()
      .reset_index()
      .sort_values(by='revenue', ascending=False)
)

product_revenue.head()

                  product_detail   revenue
75  Sustainably Grown Organic Lg  21151.75
20             Dark chocolate Lg  21006.00
48                      Latte Rg  19112.25
6                  Cappuccino Lg  17641.75
53       Morning Sunrise Chai Lg  17384.00

In [21]:
#Revenue Share (%) of Each Product
total_revenue = product_revenue['revenue'].sum()

product_revenue['revenue_share_pct'] = (
    product_revenue['revenue'] /
    total_revenue
) * 100

product_revenue.head()

                  product_detail   revenue  revenue_share_pct
75  Sustainably Grown Organic Lg  21151.75           3.026814
20             Dark chocolate Lg  21006.00           3.005957
48                      Latte Rg  19112.25           2.734962
6                  Cappuccino Lg  17641.75           2.524533
53       Morning Sunrise Chai Lg  17384.00           2.487649

In [22]:
#Comparison Between Volume Rank and Revenue Rank
#Create Sales Volume Table
product_volume = (
    df.groupby('product_detail')['transaction_qty']
      .sum()
      .reset_index()
)

In [23]:
#Add Volume Rank
product_volume['volume_rank'] = (
    product_volume['transaction_qty']
    .rank(method='dense', ascending=False)
    .astype(int)
)

In [24]:
#Add Revenue Rank
product_revenue['revenue_rank'] = (
    product_revenue['revenue']
    .rank(method='dense', ascending=False)
    .astype(int)
)
product_revenue['revenue_rank'] = (
    product_revenue['revenue']
    .rank(method='dense', ascending=False)
    .astype(int)
)

In [25]:
#Merge Both Tables
comparison = pd.merge(
    product_volume,
    product_revenue[
        ['product_detail',
         'revenue',
         'revenue_share_pct',
         'revenue_rank']
    ],
    on='product_detail'
)
comparison.head()

,product_detail,transaction_qty,volume_rank,revenue,revenue_share_pct,revenue_rank
0,Almond Croissant,1911,52,7168.13,1.025759,47
1,Brazilian - Organic,214,60,3852.00,0.551221,58
2,Brazilian Lg,4317,22,15109.50,2.162168,10
3,Brazilian Rg,4385,17,13155.00,1.882480,15
4,Brazilian Sm,4310,23,9482.00,1.356874,40

In [26]:
# save Revenue Contribution Analysis in Excel sheet
with pd.ExcelWriter(
    "Revenue_Analysis.xlsx",
    engine="openpyxl",
    mode="a",
    if_sheet_exists="replace"
) as writer:

    comparison.to_excel(
        writer,
        sheet_name="Revenue Contribution",
        index=False
    )

Category & Product-Type Performance

In [27]:
#Revenue share by category (Coffee, Tea, Chocolate)
#revenue
#category_revenue
#Revenue Share %
total_revenue = category_revenue['revenue'].sum()

category_revenue['revenue_share_pct'] = (
    category_revenue['revenue'] /
    total_revenue
) * 100

category_revenue

     product_category    revenue  revenue_share_pct
2              Coffee  269952.45          38.630178
8                 Tea  196405.95          28.105679
0              Bakery   82315.64          11.779363
4  Drinking Chocolate   72416.00          10.362725
3        Coffee beans   40085.25           5.736197
1             Branded   13607.00           1.947161
6           Loose Tea   11213.60           1.604665
5            Flavours    8408.80           1.203299
7  Packaged Chocolate    4407.64           0.630733

In [28]:
#Product-type contribution within each category
type_contribution = (
    df.groupby(
        ['product_category', 'product_type']
    )['revenue']
      .sum()
      .reset_index()
)
type_contribution

      product_category           product_type   revenue
0               Bakery               Biscotti  19793.53
1               Bakery                 Pastry  25655.99
2               Bakery                  Scone  36866.12
3              Branded               Clothing   6163.00
4              Branded             Housewares   7444.00
5               Coffee       Barista Espresso  91406.20
6               Coffee            Drip coffee  31984.00
7               Coffee  Gourmet brewed coffee  70034.60
8               Coffee  Organic brewed coffee  37746.50
9               Coffee  Premium brewed coffee  38781.15
10        Coffee beans         Espresso Beans   5560.25
11        Coffee beans          Gourmet Beans   6798.00
12        Coffee beans            Green beans   1340.00
13        Coffee beans      House blend Beans   3294.00
14        Coffee beans          Organic Beans   8509.50
15        Coffee beans          Premium Beans  14583.50
16  Drinking Chocolate          Hot chocolate  72416.00
17            Flavours          Regular syrup   6084.80
18            Flavours       Sugar free syrup   2324.00
19           Loose Tea              Black tea   2711.85
20           Loose Tea               Chai tea   4301.25
21           Loose Tea              Green tea   1470.75
22           Loose Tea             Herbal tea   2729.75
23  Packaged Chocolate     Drinking Chocolate   2728.04
24  Packaged Chocolate      Organic Chocolate   1679.60
25                 Tea       Brewed Black tea  47932.00
26                 Tea        Brewed Chai tea  77081.95
27                 Tea       Brewed Green tea  23852.50
28                 Tea      Brewed herbal tea  47539.50

In [29]:
#Contribution % Within Category
type_contribution['category_total'] = (
    type_contribution.groupby('product_category')['revenue']
    .transform('sum')
)

type_contribution['type_share_pct'] = (
    type_contribution['revenue']
    / type_contribution['category_total']
) * 100

type_contribution

,product_category,product_type,revenue,category_total,type_share_pct
0,Bakery,Biscotti,19793.53,82315.64,24.045892
1,Bakery,Pastry,25655.99,82315.64,31.167819
2,Bakery,Scone,36866.12,82315.64,44.786288
3,Branded,Clothing,6163.00,13607.00,45.292864
4,Branded,Housewares,7444.00,13607.00,54.707136
5,Coffee,Barista Espresso,91406.20,269952.45,33.860111
6,Coffee,Drip coffee,31984.00,269952.45,11.848012
7,Coffee,Gourmet brewed coffee,70034.60,269952.45,25.943310
8,Coffee,Organic brewed coffee,37746.50,269952.45,13.982648
9,Coffee,Premium brewed coffee,38781.15,269952.45,14.365919
10,Coffee beans,Espresso Beans,5560.25,40085.25,13.871062
11,Coffee beans,Gourmet Beans,6798.00,40085.25,16.958856
12,Coffee beans,Green beans,1340.00,40085.25,3.342875
13,Coffee beans,House blend Beans,3294.00,40085.25,8.217486
14,Coffee beans,Organic Beans,8509.50,40085.25,21.228507
15,Coffee beans,Premium Beans,14583.50,40085.25,36.381213
16,Drinking Chocolate,Hot chocolate,72416.00,72416.00,100.000000
17,Flavours,Regular syrup,6084.80,8408.80,72.362287
18,Flavours,Sugar free syrup,2324.00,8408.80,27.637713
19,Loose Tea,Black tea,2711.85,11213.60,24.183581
20,Loose Tea,Chai tea,4301.25,11213.60,38.357441
21,Loose Tea,Green tea,1470.75,11213.60,13.115770
22,Loose Tea,Herbal tea,2729.75,11213.60,24.343208
23,Packaged Chocolate,Drinking Chocolate,2728.04,4407.64,61.893440
24,Packaged Chocolate,Organic Chocolate,1679.60,4407.64,38.106560
25,Tea,Brewed Black tea,47932.00,196405.95,24.404556
26,Tea,Brewed Chai tea,77081.95,196405.95,39.246240
27,Tea,Brewed Green tea,23852.50,196405.95,12.144490
28,Tea,Brewed herbal tea,47539.50,196405.95,24.204715

In [30]:
#Dependence Analysis on Core Categories
#category_revenue
#Find Top 3 Category

top_categories = category_revenue.head(3)
print(top_categories)

  product_category    revenue  revenue_share_pct
2           Coffee  269952.45          38.630178
8              Tea  196405.95          28.105679
0           Bakery   82315.64          11.779363

In [31]:
#Save to Excel sheet
with pd.ExcelWriter(
    "Revenue_Analysis.xlsx",
    engine="openpyxl",
    mode="a",
    if_sheet_exists="replace"
) as writer:

    category_revenue.to_excel(
        writer,
        sheet_name="Category Performance",
        index=False
    )

    type_contribution.to_excel(
        writer,
        sheet_name="Type Contribution",
        index=False
    )

Revenue Concentration & Menu Balance

In [32]:
#Pareto (80/20) Analysis
total_revenue = product_revenue['revenue'].sum()

product_revenue['revenue_share_pct'] = (
    product_revenue['revenue'] /
    total_revenue
) * 100

In [33]:
#Calculate Cumulative Revenue %
product_revenue['cumulative_pct'] = (
    product_revenue['revenue_share_pct']
    .cumsum()
)
product_revenue.head()

,product_detail,revenue,revenue_share_pct,revenue_rank,cumulative_pct
75,Sustainably Grown Organic Lg,21151.75,3.026814,1,3.026814
20,Dark chocolate Lg,21006.00,3.005957,2,6.032771
48,Latte Rg,19112.25,2.734962,3,8.767733
6,Cappuccino Lg,17641.75,2.524533,4,11.292266
53,Morning Sunrise Chai Lg,17384.00,2.487649,5,13.779916

In [34]:
#Find Products Generating 80% Revenue
pareto_products = product_revenue[
    product_revenue['cumulative_pct'] <= 80
]

pareto_products

,product_detail,revenue,revenue_share_pct,revenue_rank,cumulative_pct
75,Sustainably Grown Organic Lg,21151.75,3.026814,1,3.026814
20,Dark chocolate Lg,21006.00,3.005957,2,6.032771
48,Latte Rg,19112.25,2.734962,3,8.767733
6,Cappuccino Lg,17641.75,2.524533,4,11.292266
53,Morning Sunrise Chai Lg,17384.00,2.487649,5,13.779916
47,Latte,17257.50,2.469547,6,16.249463
43,Jamaican Coffee River Lg,16481.25,2.358466,7,18.607929
76,Sustainably Grown Organic Rg,16233.75,2.323049,8,20.930977
5,Cappuccino,15997.50,2.289241,9,23.220219
2,Brazilian Lg,15109.50,2.162168,10,25.382387
31,Ethiopia Lg,14794.50,2.117092,11,27.499479
21,Dark chocolate Rg,14024.50,2.006905,12,29.506384
71,Spicy Eye Opener Chai Lg,13652.40,1.953658,13,31.460042
32,Ethiopia Rg,13179.00,1.885914,14,33.345956
3,Brazilian Rg,13155.00,1.882480,15,35.228435
63,Peppermint Lg,13050.00,1.867454,16,37.095890
26,English Breakfast Lg,12927.00,1.849853,17,38.945742
23,Earl Grey Lg,12735.00,1.822378,18,40.768120
68,Serenity Green Tea Lg,12660.00,1.811645,19,42.579765
14,Columbian Medium Roast Lg,12585.00,1.800913,20,44.380678
78,Traditional Blend Chai Lg,12522.00,1.791897,21,46.172575
29,Espresso shot,12495.00,1.788034,22,47.960609
44,Jamaican Coffee River Rg,12455.80,1.782424,23,49.743033
50,Lemon Grass Lg,12267.00,1.755407,24,51.498440
58,Our Old Time Diner Blend Lg,11991.00,1.715911,25,53.214352
24,Earl Grey Rg,11770.00,1.684286,26,54.898638
12,Civet Cat,11700.00,1.674269,27,56.572907
10,Chocolate Croissant,11625.98,1.663677,28,58.236584
54,Morning Sunrise Chai Rg,11607.50,1.661033,29,59.897617
64,Peppermint Rg,11410.00,1.632770,30,61.530387
15,Columbian Medium Roast Rg,11367.50,1.626689,31,63.157075
79,Traditional Blend Chai Rg,11280.00,1.614167,32,64.771243
69,Serenity Green Tea Rg,11192.50,1.601646,33,66.372889
59,Our Old Time Diner Blend Rg,11025.00,1.577677,34,67.950565
51,Lemon Grass Rg,10812.50,1.547268,35,69.497834
72,Spicy Eye Opener Chai Rg,10636.05,1.522018,36,71.019852
27,English Breakfast Rg,10500.00,1.502549,37,72.522401
45,Jamaican Coffee River Sm,9844.10,1.408690,38,73.931091
33,Ethiopia Sm,9752.60,1.395596,39,75.326687
4,Brazilian Sm,9482.00,1.356874,40,76.683561
60,Our Old Time Diner Blend Sm,8968.00,1.283320,41,77.966881
66,Scottish Cream Scone,8949.45,1.280666,42,79.247547

In [35]:
#Count Products Driving 80% Revenue
num_products = len(pareto_products)

total_products = len(product_revenue)

print(
    f"{num_products} out of {total_products} products generate 80% of revenue"
)

42 out of 80 products generate 80% of revenue

In [36]:
#Identify Revenue Anchors
revenue_anchors = product_revenue.head(10)

revenue_anchors

,product_detail,revenue,revenue_share_pct,revenue_rank,cumulative_pct
75,Sustainably Grown Organic Lg,21151.75,3.026814,1,3.026814
20,Dark chocolate Lg,21006.00,3.005957,2,6.032771
48,Latte Rg,19112.25,2.734962,3,8.767733
6,Cappuccino Lg,17641.75,2.524533,4,11.292266
53,Morning Sunrise Chai Lg,17384.00,2.487649,5,13.779916
47,Latte,17257.50,2.469547,6,16.249463
43,Jamaican Coffee River Lg,16481.25,2.358466,7,18.607929
76,Sustainably Grown Organic Rg,16233.75,2.323049,8,20.930977
5,Cappuccino,15997.50,2.289241,9,23.220219
2,Brazilian Lg,15109.50,2.162168,10,25.382387

In [37]:
#Identify Long-Tail Products
long_tail_products = product_revenue.tail(20)

long_tail_products

,product_detail,revenue,revenue_share_pct,revenue_rank,cumulative_pct
39,I Need My Bean! Diner mug,2935.00,0.419998,61,95.282526
42,Jamacian Coffee River,2883.50,0.412629,62,95.695155
28,Espresso Roast,2492.75,0.356712,63,96.051867
73,Sugar Free Vanilla syrup,2324.00,0.332564,64,96.384431
13,Columbian Medium Roast,2220.00,0.317682,65,96.702113
11,Chocolate syrup,2126.40,0.304288,66,97.006401
7,Carmel syrup,2060.80,0.294900,67,97.301301
8,Chili Mayan,1972.84,0.282313,68,97.583614
38,Hazelnut syrup,1897.60,0.271546,69,97.855161
74,Sustainably Grown Organic,1679.60,0.240351,70,98.095512
52,Morning Sunrise Chai,1596.00,0.228387,71,98.323899
67,Serenity Green Tea,1470.75,0.210464,72,98.534363
25,English Breakfast,1440.95,0.206200,73,98.740563
77,Traditional Blend Chai,1369.35,0.195954,74,98.936517
62,Peppermint,1369.35,0.195954,74,99.132471
49,Lemon Grass,1360.40,0.194673,75,99.327144
36,Guatemalan Sustainably Grown,1340.00,0.191754,76,99.518898
70,Spicy Eye Opener Chai,1335.90,0.191167,77,99.710065
22,Earl Grey,1270.90,0.181866,78,99.891931
19,Dark chocolate,755.20,0.108069,79,100.000000

In [38]:
#Revenue Contribution of Long Tail
long_tail_share = (
    long_tail_products['revenue'].sum()
    / total_revenue
) * 100

print(long_tail_share)

5.137472316780673

In [39]:
#Menu Diversification Risk
#Top 5 Product Concentration
top5_revenue = (
    product_revenue.head(5)['revenue']
    .sum()
)

top5_ratio = (
    top5_revenue /
    total_revenue
) * 100

print(top5_ratio)

13.779915703548046

In [40]:
#Save Result
with pd.ExcelWriter(
    "Revenue_Analysis.xlsx",
    engine="openpyxl",
    mode="a",
    if_sheet_exists="replace"
) as writer:

    product_revenue.to_excel(
        writer,
        sheet_name="Pareto Analysis",
        index=False
    )

    revenue_anchors.to_excel(
        writer,
        sheet_name="Revenue Anchors",
        index=False
    )

    long_tail_products.to_excel(
        writer,
        sheet_name="Long Tail Products",
        index=False
    )

In [41]:
file = pd.ExcelFile("Revenue_Analysis.xlsx")

print(file.sheet_names)

['Product Revenue', 'Product Type Revenue', 'Category Revenue', 'Product Popularity', 'Revenue Contribution', 'Category Performance', 'Type Contribution', 'Pareto Analysis', 'Revenue Anchors', 'Long Tail Products']

KPI Calculation

In [42]:
#Product Revenue Contribution (%)
product_revenue = (
    df.groupby('product_detail')['revenue']
      .sum()
      .reset_index()
)

total_revenue = product_revenue['revenue'].sum()

product_revenue['revenue_contribution_pct'] = (
    product_revenue['revenue'] /
    total_revenue
) * 100

product_revenue.sort_values(
    by='revenue_contribution_pct',
    ascending=False
).head()

                  product_detail   revenue  revenue_contribution_pct
75  Sustainably Grown Organic Lg  21151.75                  3.026814
20             Dark chocolate Lg  21006.00                  3.005957
48                      Latte Rg  19112.25                  2.734962
6                  Cappuccino Lg  17641.75                  2.524533
53       Morning Sunrise Chai Lg  17384.00                  2.487649

In [43]:
#Product Sales Volume
product_volume = (
    df.groupby('product_detail')['transaction_qty']
      .sum()
      .reset_index()
      .sort_values(
          by='transaction_qty',
          ascending=False
      )
)

product_volume.head()

             product_detail  transaction_qty
24             Earl Grey Rg             4708
20        Dark chocolate Lg             4668
54  Morning Sunrise Chai Rg             4643
47                    Latte             4602
64            Peppermint Rg             4564

In [44]:
#Category Revenue Share
category_revenue = (
    df.groupby('product_category')['revenue']
      .sum()
      .reset_index()
)

total_revenue = category_revenue['revenue'].sum()

category_revenue['category_share_pct'] = (
    category_revenue['revenue']
    / total_revenue
) * 100

category_revenue

     product_category    revenue  category_share_pct
0              Bakery   82315.64           11.779363
1             Branded   13607.00            1.947161
2              Coffee  269952.45           38.630178
3        Coffee beans   40085.25            5.736197
4  Drinking Chocolate   72416.00           10.362725
5            Flavours    8408.80            1.203299
6           Loose Tea   11213.60            1.604665
7  Packaged Chocolate    4407.64            0.630733
8                 Tea  196405.95           28.105679

In [45]:
#Revenue Concentration Ratio
product_revenue = (
    df.groupby('product_detail')['revenue']
      .sum()
      .sort_values(ascending=False)
)

top5_revenue = product_revenue.head(5).sum()

total_revenue = product_revenue.sum()

revenue_concentration_ratio = (
    top5_revenue /
    total_revenue
) * 100

print(revenue_concentration_ratio)

13.779915703548046

In [46]:
#Product Efficiency Score
total_revenue = df['revenue'].sum()

sku_count = df['product_detail'].nunique()

product_efficiency_score = (
    total_revenue /
    sku_count
)

print(product_efficiency_score)

8735.154125000001

In [47]:
#Product-Level Efficiency
product_efficiency = (
    df.groupby('product_detail')['revenue']
      .sum()
      .reset_index()
      .sort_values(
          by='revenue',
          ascending=False
      )
)

In [48]:
#save these kpi in existing file but in new sheet
with pd.ExcelWriter(
    "Data/Cleaned_Afficionado_Coffee_Data.xlsx",
    engine="openpyxl",
    mode="a",
    if_sheet_exists="replace"
) as writer:

    product_revenue.to_excel(
        writer,
        sheet_name="Product Revenue KPI",
        index=False
    )

    product_volume.to_excel(
        writer,
        sheet_name="Product Volume KPI",
        index=False
    )

    category_revenue.to_excel(
        writer,
        sheet_name="Category Revenue KPI",
        index=False
    )

SQL Connections

In [55]:
#install package
!pip install psycopg2-binary sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg2-binary in c:\users\pooja\appdata\roaming\python\python314\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\users\pooja\appdata\roaming\python\python314\site-packages (2.0.50)
Requirement already satisfied: greenlet>=1 in c:\users\pooja\appdata\roaming\python\python314\site-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\pooja\appdata\roaming\python\python314\site-packages (from sqlalchemy) (4.15.0)

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [50]:
df.to_excel('data/Cleaned_Afficionado_Coffee_Data.xlsx')

In [53]:
from sqlalchemy import create_engine
# Step 1: Connect to PostgreSQL
# Replace placeholders with your actual details
username = "postgres"      # default user
password = "pooja" # the password you set during installation
host = "localhost"         # if running locally
port = "5432"              # default PostgreSQL port
database = "Afficionado_CoffeeDB"    # the database you created in pgAdmin
engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

In [54]:
# Step 2: Load DataFrame into PostgreSQL
table_name = "Retail_data"   # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)
print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'Retail_data' in database 'Afficionado_CoffeeDB'.